# .github/cp-kit-models.yaml
# Matriz de Alocação de Modelos v3.0 (Full 20-Agent Suite)
# Strategy: Architect-Builder Pattern (Hybrid) + Community Consensus 2026

defaults:
  temperature_planner: 0.1 # Raciocínio frio
  temperature_executor: 0.3 # Criatividade controlada para código
  fallback_model: "gpt-5.1-codex"

agents:
  # ==============================================================================
  # 1. LIDERANÇA E ESTRATÉGIA (Pure Reasoning)
  # ==============================================================================
  orchestrator:
    mode: "single"
    model: "claude-opus-4.5"
    reason: "Capacidade superior de manter o contexto de múltiplos agentes e passos."

  product-manager:
    mode: "single"
    model: "gpt-5.2"
    reason: "Equilíbrio ideal entre visão de negócios e viabilidade técnica."

  product-owner:
    mode: "single"
    model: "gemini-3-pro" # (Preview)
    reason: "Context window massiva para ingerir todo o histórico e backlog do produto."

  project-planner:
    mode: "single"
    model: "gpt-5.2"
    reason: "Lógica temporal robusta para cronogramas, dependências e caminho crítico."

  # ==============================================================================
  # 2. DESENVOLVIMENTO CORE (Architect-Builder Hybrid)
  # ==============================================================================
  backend-specialist:
    mode: "hybrid"
    planner:
      model: "gpt-5.2"
      task: "Arquitetura de API, segurança e modelagem de dados."
    executor:
      model: "gpt-5.2-codex"
      task: "Implementação estrita de rotas e serviços com tipagem perfeita."

  frontend-specialist:
    mode: "hybrid"
    planner:
      model: "claude-opus-4.5"
      task: "Definição de UX, Acessibilidade e Component Tree."
    executor:
      model: "claude-sonnet-4.5"
      task: "Geração de React/CSS visualmente fiel e sem alucinações de layout."

  mobile-developer:
    mode: "hybrid"
    planner:
      model: "claude-opus-4.5"
      task: "Arquitetura nativa vs híbrida e gerenciamento de estado complexo."
    executor:
      model: "claude-sonnet-4.5"
      task: "Escrita de SwiftUI/Kotlin com sintaxe declarativa aninhada."

  game-developer:
    mode: "hybrid"
    planner:
      model: "gpt-5.2"
      task: "Design de sistemas de jogo, física e loop principal."
    executor:
      model: "gpt-5.1-codex-max"
      task: "Cálculos vetoriais pesados e otimização de C++/C#."

  # ==============================================================================
  # 3. INFRAESTRUTURA E OPERAÇÕES (High Cost Savings)
  # ==============================================================================
  devops-engineer:
    mode: "hybrid"
    planner:
      model: "claude-opus-4.5"
      task: "Estratégia de Cloud, segurança de pipelines e disaster recovery."
    executor:
      model: "grok-code-fast-1" # Economia extrema aqui
      task: "Geração rápida de YAMLs, Dockerfiles e scripts Bash."

  database-architect:
    mode: "hybrid"
    planner:
      model: "gpt-5.2"
      task: "Modelagem ER, normalização e estratégia de indexação."
    executor:
      model: "gpt-5.1-codex"
      task: "Geração de SQL complexo, migrations e triggers."

  security-auditor:
    mode: "single"
    model: "claude-opus-4.5"
    reason: "Raciocínio paranoico necessário para auditoria (Red Teaming)."

  penetration-tester:
    mode: "hybrid"
    planner:
      model: "gpt-5.2"
      task: "Planejamento de vetores de ataque e engenharia social."
    executor:
      model: "gpt-5.2-codex"
      task: "Criação de exploits e scripts de teste de penetração."

  # ==============================================================================
  # 4. QUALIDADE E OTIMIZAÇÃO
  # ==============================================================================
  qa-automation-engineer:
    mode: "hybrid"
    planner:
      model: "gpt-5.2"
      task: "Estratégia de testes E2E e cobertura de cenários críticos."
    executor:
      model: "gpt-5.1-codex-mini" # (Preview)
      task: "Escrita em massa de scripts Cypress/Playwright."

  test-engineer:
    mode: "single"
    model: "gpt-5.1-codex-max"
    reason: "Foco total em cobertura de testes unitários e mocks."

  debugger:
    mode: "single"
    model: "claude-opus-4.5"
    reason: "Melhor modelo para análise causal de logs e stack traces."

  performance-optimizer:
    mode: "hybrid"
    planner:
      model: "gpt-5.2"
      task: "Profiling e identificação de gargalos algorítmicos."
    executor:
      model: "gpt-5.1-codex-max"
      task: "Refatoração de código para redução de complexidade Big O."

  # ==============================================================================
  # 5. ESPECIALISTAS E PESQUISA
  # ==============================================================================
  code-archaeologist:
    mode: "hybrid"
    planner:
      model: "gemini-3-pro" # (Preview)
      task: "Leitura de todo o repositório legado para entender dependências."
    executor:
      model: "gpt-5.1-codex"
      task: "Refatoração cirúrgica sem quebrar compatibilidade."

  documentation-writer:
    mode: "single"
    model: "claude-sonnet-4.5"
    reason: "Texto técnico mais natural, empático e bem formatado."

  seo-specialist:
    mode: "single"
    model: "gemini-3-flash" # (Preview)
    reason: "Acesso rápido a dados da web e tendências de busca em tempo real."

  explorer-agent:
    mode: "single"
    model: "raptor-mini" # (Preview)
    reason: "Pensamento lateral rápido e brainstorming divergente."